spring:
  datasource:
    url: jdbc:mysql://localhost/schooldb
    username: spring
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id:
#            client-secret:
#            scope:
#              - user:email
#              - read:user
#          google:
#            client-id:
#            client-secret: